version: '3'

services:
  django:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://omar.abuelenen:password@db:5432/user_dashboard
    volumes:
      - ./backend:/app

  react:
    build: ./frontend
    ports:
      - "3000:3000"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_dashboard
      POSTGRES_USER: omar.abuelenen
      POSTGRES_PASSWORD: password
